### ISSUE TITLE
Crash on startup with Spell Engine 1.10.3 — `NoSuchMethodError: LootConfig.constrainValues`

### ISSUE THREAD

**Issue by Drehverschluss** [ProfessorFichte/Witcher#18]
**Mod version:** witcher-class-mod-neoforge 3.1.0+1.21.1
**Minecraft:** 1.21.1, NeoForge
**Spell Engine version:** 1.10.3+1.21.1
**Other info:** Crash happens on any client/server startup with this Spell Engine version installed, before the world even loads. Worked fine with Spell Engine 1.10.2.

**Description:**
Since updating Spell Engine to 1.10.3, the game crashes while constructing the witcher_rpg mod instance:

```
Failed to create mod instance. ModID: witcher_rpg, class com.witcher.neoforge.NeoForgeMod
java.lang.NoSuchMethodError: 'net.spell_engine.rpg_series.loot.LootConfig net.spell_engine.rpg_series.loot.LootConfig.constrainValues(net.spell_engine.rpg_series.loot.LootConfig)'
	at witcher_rpg@3.1.0/net.witcher_rpg.WitcherClassMod.<clinit>(WitcherClassMod.java:82)
	at witcher_rpg@3.1.0/com.witcher.neoforge.NeoForgeMod.<init>(NeoForgeMod.java:17)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:122)
	at net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153)
	... (ForkJoinPool frames)
```

Looks like `WitcherClassMod`'s static initializer calls `LootConfig.constrainValues(LootConfig)` from Spell Engine's `net.spell_engine.rpg_series.loot.LootConfig` API, and that method's signature has changed (or been removed) in Spell Engine 1.10.3 — witcher_rpg 3.1.0 was presumably built against an older Spell Engine API version.

Downgrading to Spell Engine 1.10.2 avoids the crash. I don't need a fix for my own pack anymore (removed the class from my modpack), but wanted to flag it in case others hit it with newer Spell Engine releases.

Happy to provide the full crash report / log if useful.

**Comment by Daniel-v01** [comment]
[debug.log](https://github.com/user-attachments/files/31431165/debug.log)

had the same proble, fixed by downgrading Spell Engine too
i'm uploading the logs in case they may be useful

and thanks Drehverschluss for opening the issue, it helped us a lot

**Comment by Drehverschluss** [comment]
Hehe no problem :)

**Comment by ProfessorFichte** [comment]
should be fixed now
